### ISSUE TITLE
All combinations of course, diet, allergy

### ISSUE THREAD

**Issue by ArpitaDixit** [virajnilakh/ZenHealth#26]

**Comment by ArpitaDixit** [comment]
Add in Yummly credentials doc

**Comment by ArpitaDixit** [comment]
Allowed Allergy Values:
Dairy, Egg, Gluten, Peanut, Seafood, Sesame, Soy, Sulfite, Tree Nut, Wheat
If we take all combinations of allergies it will be 10! i.e 36,28,800 queries.. Which is a lot. adding  on top of this courses, diets and L|M|H will lead to a lot of queries. 
So how should i proceed?

**Comment by amdh** [comment]
Did not get your question...when can we have discussion?

**Comment by ArpitaDixit** [comment]
Will complete this after I get a response from Prof and Vidhu. Dependant on Issue 29 and 28

**Comment by ArpitaDixit** [comment]
All allergies used once. Combinations ignored
